- src/bindings/html/dom.js
- src/bindings/html/service.js
- src/bindings/html/view.js
I'm pretty sure we can do this prettier, but it's the first try :)
@stasm - thoughts?
> Introduce pretranslation

- src/bindings/html/dom.js
Didn't measure perf/mem on this yet
> Turn off MutationObserver while translating DOM

- src/bindings/gaiabuild/serialize.js
- src/bindings/gaiabuild/view.js
- src/bindings/html/dom.js
- src/bindings/html/head.js
- src/bindings/html/langs.js
- src/bindings/html/service.js
- src/bindings/html/view.js
- src/lib/context.js
- src/lib/env.js
- src/lib/events.js
- src/lib/intl.js
- src/lib/plurals.js
- src/lib/pseudo.js
- src/lib/resolver.js
- src/runtime/gaiabuild/index.js
- src/runtime/node/io.js
- src/runtime/web/index.js
- src/runtime/web/io.js
Let's do this.
(This is very easy to rebase, so I'm fine waiting for #42 first.)
> Use const and let

- src/bindings/gaiabuild/legacy/env.js
- src/lib/env.js
- src/lib/format/l20n/parser.js
- src/lib/format/properties/parser.js
- src/lib/mocks.js
- src/lib/pseudo.js
- src/lib/resolver.js
- src/runtime/jsshell/index.js
- src/runtime/node/index.js
- tests/lib/parser/l20n/parser_test.js
- tests/lib/parser/properties/parser_test.js
- tests/lib/pseudo_test.js
- tests/lib/resolver/primitives_test.js
- tests/lib/util_test.js
- tools/format.js
- tools/perf/benchmark.jsshell.js
- tools/perf/benchmark.node.js
- tools/perf/example.l20n
- tools/perf/example.properties
I still have some tweaks to do here and there, but it passes tests and lint. @stasm - r?
> V3 runtime parser

- src/bindings/gaiabuild/legacy/serialize.js
- src/bindings/gaiabuild/serialize.js
- src/bindings/gaiabuild/view.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1182406
> Serialize l20n to object

- src/lib/format/l20n/ast/parser.js
For aisle, I need position info in the JunkEntries.
Note, I also fixed a bug compared to my previous version, which was giving the wrong start position for the JunkEntry
> Add position to JunkEntry.

- src/lib/resolver.js
- tests/lib/context/basic_test.js
- tests/lib/context/format_test.js
- tests/lib/resolver/attributes_test.js
- tests/lib/resolver/ctxdata_test.js
- tests/lib/resolver/dos_test.js
- tests/lib/resolver/errors_test.js
- tests/lib/resolver/indexes_test.js
- tests/lib/resolver/macros_test.js
- tests/lib/resolver/primitives_test.js
- tests/lib/util.js
> Always wrap placeables in FSI/PDI

- src/bindings/html/dom.js
> Remove support for .innerHTML

- src/bindings/html/dom.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1190539
> Bug 1190539 - Escape HTML in args

- src/bindings/html/dom.js
- src/bindings/html/view.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1195539
> Bug 1195539 - Filter out non-l10n elements from translateMutations and remove condition race

- src/bindings/html/dom.js
- src/bindings/html/overlay.js
No code changes, just putting overlays-specific code in its own module for better readability.
> Separate DOM translation functions and DOM overlays

- src/bindings/html/dom.js
- src/bindings/html/service.js
- src/bindings/html/view.js
- src/runtime/web/index.js
Make `service` swappable in `view` so that we can have different services for different runtimes.
> Remove view.ctx

- src/lib/pseudo.js
A new, cleaner approach which obsoletes #36.  @zbraniecki r? Can you also help me by testing the memory of this change?
> Create pseudolanguages lazily

- src/bindings/gaiabuild/view.js
- src/bindings/html/dom.js
- src/bindings/html/service.js
- src/bindings/html/view.js
- src/lib/context.js
- tests/lib/context/basic_test.js
- tests/lib/context/format_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1196009
> Bug 1196009 - Bring back View.formatValue

- src/bindings/html/view.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1204067
> Bug 1204067 - Expose qps

- Gruntfile.js
- build/babel/index.js
- src/runtime/gaia/index.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1204660
> Bug 1204660 - Introduce a temporary proxy for l20n.js to mimic l10n.js API

- src/bindings/gaiabuild/view.js
- src/bindings/html/dom.js
- src/bindings/html/service.js
- src/bindings/html/view.js
- src/lib/context.js
- tests/lib/context/basic_test.js
- tests/lib/context/format_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1204086
> Bug 1204086 - Add formatValues API

- src/bindings/html/service.js
- src/bindings/html/view.js
- src/lib/context.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1207121
> Bug 1207121 - Guard ctx._resolve with ctx.fetch

- src/bindings/gaiabuild/view.js
- src/bindings/html/head.js
- src/bindings/html/view.js
- src/runtime/tooling/index.js
- src/runtime/web/index.js
- src/runtime/web/service.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1207120
> Bug 1207120 - Make all public View methods available during DOM loading

- src/lib/context.js
- src/lib/mocks.js
- src/lib/resolver.js
- tests/lib/context/basic_test.js
- tests/lib/resolver/attributes_test.js
- tests/lib/resolver/ctxdata_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1208800
> Bug 1208800 - Format integers passed as arguments

- docs/html.md
- docs/view.md
- src/bindings/html/view.js
- src/runtime/gaia/index.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1209363
> DOMRetranslated

- src/bindings/gaiabuild/legacy/env.js
- src/bindings/gaiabuild/view.js
- src/bindings/html/langs.js
- src/bindings/html/view.js
- src/lib/env.js
- src/lib/pseudo.js
- src/runtime/gaiabuild/index.js
- src/runtime/tooling/index.js
- src/runtime/web/service.js
- tests/lib/pseudo_test.js
- tools/pseudo.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1210721
> Bug 1210721 - Make view.pseudo async

- src/runtime/bridge/client.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1214138
> Bug 1214138 - Connect the client on pageshow; disconnect it on pagehide

- docs/view.md
- src/bindings/gaiabuild/view.js
- src/bindings/html/langs.js
- src/bindings/html/remote.js
- src/bindings/html/shims.js
- src/bindings/html/view.js
- src/lib/mocks.js
- tests/lib/context/basic_test.js
- tests/lib/context/format_test.js
- tests/lib/env/resCache.js
- tools/perf/benchmark.jsshell.js
- tools/perf/benchmark.node.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1215123
> Bug 1215123 - Remove document.l10n.resolvedLanguages

- src/bindings/html/shims.js
- src/bindings/html/view.js
- src/lib/pseudo.js
- tests/lib/pseudo_test.js
- tools/pseudo.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1190593
> Bug 1190593 - Rename qps-ploc to en-x-psaccent, qps-plocm to ar-x-psbidi.

- src/bindings/html/view.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1219208
> Bug 1219208 - Always set html.langs. r=gandalf

- src/bindings/html/langs.js
- src/bindings/html/shims.js
- src/lib/context.js
- src/lib/shims.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1221821
> Bug 1221821 - Enable support for evergreen browsers

- src/lib/format/l20n/ast/parser.js
- src/lib/format/l20n/entries/parser.js
- tests/lib/parser/l20n/parser_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1222055
> Bug 1222055 - Error on unresolvable hash value

- src/bindings/html/langs.js
- src/bindings/html/remote.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1231219
> Bug 1231219 - getAdditionalLanguages returns an object not an array. r=gandalf

- examples/bridge/view1.html
- examples/bridge/view2.html
- src/bindings/gaiabuild/legacy/env.js
- src/bindings/gaiabuild/view.js
- src/bindings/html/dom.js
- src/bindings/html/head.js
- src/bindings/html/langs.js
- src/bindings/html/remote.js
- src/bindings/html/view.js
- src/lib/context.js
- src/lib/env.js
- src/runtime/bridge/client.js
- src/runtime/bridge/service.js
- src/runtime/gaia/build/io.js
- src/runtime/node/io.js
- src/runtime/web/index.js
- src/runtime/web/io.js
- tests/lib/context/basic_test.js
- tests/lib/context/format_test.js
- tests/lib/env/resCache.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1228348
> Bug 1228348 - Allow l20n-service to run in a worker context

- src/lib/context.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1231585
> Bug 1231585 - Use groupings in l10n formatting

- src/bindings/gaiabuild/view.js
- src/bindings/html/dom.js
- src/bindings/html/observer.js
- src/bindings/html/view.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1231217
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/l20n/l20n.js/105)
> Bug 1231217 - Create API for observing new roots. r=gandalf

- src/lib/format/properties/parser.js
- tests/lib/parser/properties/parser_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1230489
> Bug 1230489 - Fix Properties parser mistakenly reacting to entity name matching key name

- src/bindings/gaiabuild/legacy/context.js
- src/bindings/gaiabuild/legacy/env.js
- src/bindings/gaiabuild/legacy/serialize.js
- src/bindings/gaiabuild/serialize.js
- src/bindings/gaiabuild/view.js
- src/bindings/html/dom.js
- src/bindings/html/observer.js
- src/bindings/html/remote.js
- src/bindings/html/view.js
- src/lib/context.js
- src/lib/env.js
- src/runtime/bridge/service.js
- tests/lib/context/basic_test.js
- tests/lib/context/format_test.js
- tests/lib/env/resCache.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1231418
> Bug 1231418 - Make Contexts immutable

- src/bindings/html.js
- src/runtime/gecko/l20n-html.js
- src/runtime/gecko/l20n-xul.js
- src/runtime/gecko/localization.js
Changes required to make the demo for MozLondon work.
> GeckoLocalization

- src/intl/plurals.js
Covers polish plural case with decimals. For example, 0,3⁩ sekundy and 4,3⁩ sekundy.
> Update Polish decimal case

- src/runtime/gecko/makefile
- src/runtime/gecko/rollup.config.js
- src/runtime/gecko/xpcom.rollup.config.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1288687
> Bug 1288687 - Fix mozilla-central's linting errors

- tools/perf/benchmark.d8.js
- tools/perf/benchmark.jsshell.js
- tools/perf/benchmark.node.js
- tools/perf/example.ftl
https://bugzilla.mozilla.org/show_bug.cgi?id=1297434
> Bug 1297434 - Update `make perf` examples with menubar strings

- src/intl/context.js
- src/intl/resolver.js
- src/lib/dom/base.js
- src/lib/format.js
- src/lib/observer/base.js
- tools/perf/benchmark.d8.js
- tools/perf/benchmark.jsshell.js
- tools/perf/benchmark.node.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1296618
> Bug 1296618 - Optimize message formatting

- docs/hacking.rst
I want to do another run through it, but I think it's ready for review.
> Introduce hacking.rst

- docs/gecko.rst
- docs/syntax.rst
@zbraniecki what do you think?
> Using L20n To Localize XUL Documents

- docs/localization.md
- src/lib/dom/base.js
- src/lib/dom/html.js
- src/lib/dom/overlay.js
- src/lib/dom/xul.js
- src/runtime/gecko/util.js
Includes changes to the code -- I realized that in a few places it was overly verbose.
> Docstrings for src/lib/dom

- src/intl/resolver.js
- src/lib/dom/base.js
- src/lib/format.js
- src/lib/observer/base.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1306262
> Bug 1306262 - Wrapping in Bidi Isolation marks should happen in bindings

- src/runtime/gecko/l20n-chrome-html.js
- src/runtime/gecko/l20n-chrome-xbl.js
- src/runtime/gecko/l20n-chrome-xul.js
- src/runtime/gecko/util.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1308896
> Bug 1308896 - Remove Services.obs code that we don't use right now

- docs/hacking.rst
I applied the feedback we got on the first iteration of the Hacking documentation.
@Pike, @zbraniecki — r?
> Second pass on hacking.rst

- src/runtime/testing/index.js
- src/runtime/testing/io.js
- test/bindings/dom.js
> Add a test to Karma that tests whole cycle of dom l10n

- docs/gecko.rst
- docs/syntax.rst
> Address feedback on gecko.rst

- docs/syntax.rst
> Address feedback for the syntax.rst

- docs/builtins.rst
> Add builtins docs

- docs/builtins.rst
- docs/syntax.rst
- examples/locales/example.en-US.ftl
- src/intl/builtins.js
- test/intl/functions_builtin_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1311662
> Bug 1311662 - Remove the PLURAL builtin function

- package.json
- src/ftl/ast/parser.js
- src/ftl/entries/parser.js
- src/intl/plurals.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1314595
> Bug 1314595 - Add spaced-comment linting rule.

- docs/gecko.rst
- docs/syntax.rst
https://bugzilla.mozilla.org/show_bug.cgi?id=1306011
> Bug 1306011 - Prepare the docs to land in mozilla-central

- docs/messagecontext.md
- src/intl/context.js
- src/intl/resolver.js
- src/lib/localization.js
- test/bindings/document_localization.js
- test/bindings/dom_localization.js
- test/intl/arguments_test.js
- test/intl/bomb_test.js
- test/intl/context_test.js
- test/intl/functions_builtin_test.js
- test/intl/functions_runtime_test.js
- test/intl/functions_test.js
- test/intl/isolating_test.js
- test/intl/patterns_test.js
- test/intl/primitives_test.js
- test/intl/select_expressions_test.js
- test/intl/traits_test.js
- test/intl/values_format_test.js
- test/intl/values_ref_test.js
- test/lib/localization_fallback_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1317989
> Bug 1317989 - Move bidi wrapping back into MessageContext

- src/ftl/ast/ast.js
- src/ftl/ast/parser.js
- src/ftl/ast/serializer.js
This PR ports the changes to the Python implementation made in https://bugzilla.mozilla.org/show_bug.cgi?id=1316640.
> Bug 1316640 - Create a module for migrating legacy translations to FTL

- src/runtime/gecko/l20n.js
- src/runtime/web/index.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1315811
> Bug 1315811 - Add document.l10n.ready
